//
// This code is not elegant and is a modified version of what 
// appeared in Adobe Developer Connection. 
//
// Parse related keys
var PARSE_APP = "<place_your_app_key_here>";
var PARSE_JS = "<place_your_javascript_key_here>";

$(document).ready(function() {

  // Required before doing anything with Parse
  Parse.initialize(PARSE_APP, PARSE_JS);

  // Datasource here is called things but can be note, foobar, or whatever you want
  // Just make certain to create it first before you reference it.
  // This example was created via the data browser at Parse.com for a specific app
        NoteObject = Parse.Object.extend("things");

        function getNotes() {
                var query = new Parse.Query(NoteObject);

                query.find({
                        success:function(results) {
                                console.dir(results);
                                var s = "";
                                for(var i=0, len=results.length; i<len; i++) {
                                        var note = results[i];
                                        s += "<p>";
          // these fields should be defined in your collection at parse.com
          // the timedate stamp is autogenerated by parse.com
          s += "<b>"+note.get("title")+"</b><br/>";
          s += "<b>"+note.get("subject")+"</b><br/>";
                                        s += "<b>Written "+note.createdAt + "<br/>";
                                        s += note.get("body");
                                        s += "</p>";
                                }
                                $("#notes").html(s);
                        },
                        error:function(error) {
                                alert("Error when getting notes!");
                        }
                });
        }

        $("#addNoteBtn").on("click", function(e) {
                e.preventDefault();

                //Grab the note details, no real validation for now
    var title = $("#noteTitle").val();
    var subject = $("#noteSubject").val();
                var body = $("#noteBody").val();

                var note = new NoteObject();
                note.save({title:title, subject:subject, body:body}, {
                        success:function(object) {
                                console.log("Saved the object!");
                                $("#noteTitle").val("");
                                $("#noteSubject").val("");
                                $("#noteBody").val("");
                                getNotes();
                        }, 
                        error:function(object,error) {
                                console.dir(error);
                                alert("Sorry, I couldn't save it.");
                        }
                });
        });

        //call getNotes immediately
        getNotes();

});
        
