//
// This code is not elegant and is a modified version of what 
// appeared in Adobe Developer Connection. 
//
// Parse related keys
var PARSE_APP = "<XXZlaAipEmrclrqZrPn1SBxbwrXAx2hgofvnUZ33>";
var PARSE_JS = "<5GIQWHQBqwzX2cgfQb3OGLwWtSZ31c5Jm8YIAY96>";

$(document).ready(function() {

  // Required before doing anything with Parse
  Parse.initialize(PARSE_APP, PARSE_JS);

  // Datasource here is called things but can be note, foobar, or whatever you want
  // Just make certain to create it first before you reference it.
  // This example was created via the data browser at Parse.com for a specific app
        Show = Parse.Object.extend("Show");

        function getShow() {
                var query = new Parse.Query(Show);

                query.find({
                        success:function(results) {
                                console.dir(results);
                                var s = "";
                                for(var i=0, len=results.length; i<len; i++) {
                                        var show = results[i];
                                        s += "<p>";
          // these fields should be defined in your collection at parse.com
          // the timedate stamp is autogenerated by parse.com
          s += "<b>"+show.get("HeadLiner")+"</b><br/>";
          s += "<b>"+show.get("Venue")+"</b><br/>";
                                        s += "<b>Written "+show.createdAt + "<br/>";
                                        s += show.get("body");
                                        s += "</p>";
                                }
                                $("#show").html(s);
                        },
                        error:function(error) {
                                alert("Error when getting notes!");
                        }
                });
        }

        $("#addShowBtn").on("click", function(e) {
                e.preventDefault();

                //Grab the note details, no real validation for now
    var title = $("#ShowHeadLiner").val();
    var subject = $("#ShowVenue").val();
                var body = $("#ShowBody").val();

                var Show = new Show();
                show.save({Headliner:Headliner, Venue:Venue, DateRange:DateRange}, {
                        success:function(object) {
                                console.log("Saved the object!");
                                $("#ShowHeadLiner").val("");
                                $("#ShowVenue").val("");
                                $("#ShowDateRange").val("");
                                getShow();
                        }, 
                        error:function(object,error) {
                                console.dir(error);
                                alert("Sorry, I couldn't save it.");
                        }
                });
        });

        //call getShow immediately
        getShow();

});
        
